"""Agrega campo activo

Revision ID: d9aa900ce2ec
Revises: f8f3b686dbbf
Create Date: 2025-06-06 14:06:55.813412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9aa900ce2ec'
down_revision = 'f8f3b686dbbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('libro', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
